soul:
  package_name: "cn.soulapp.android"
  chat_activity: ".cpnt_voiceparty.soulhouse.SoulHouseActivity"
  elements:
    message_list: "cn.soulapp.android:id/rvMessage"
    message_content: "cn.soulapp.android:id/tvContent"
    input_box_entry: "cn.soulapp.android:id/tvChat"
    input_box: "cn.soulapp.android:id/etInputView"
    button_send: "cn.soulapp.android:id/btnSend"
    new_message_tip: "cn.soulapp.android:id/tvNewMsgTip"
    floating_entry: "cn.soulapp.android:id/background"
    invite_link: "cn.soulapp.android:id/iv_room_music"
    sender_relation: "cn.soulapp.android:id/imgRelation"
    sender_flag: "cn.soulapp.android:id/flagContainerView"
    sender_avatar: "cn.soulapp.android:id/ivAvatar"
    sender_nickname: "cn.soulapp.android:id/tvNickname"
    profile_avatar: "cn.soulapp.android:id/img_head"
    moments_chat: "cn.soulapp.android:id/rl_user_bottom_chat"
    chat_title: "cn.soulapp.android:id/c_ct_chat_title_info"
    manager_invite: "cn.soulapp.android:id/tv_manager_invite"
    confirm_invite: "cn.soulapp.android:id/tv_confirm_invite"
    confirm_dismiss: "//android.widget.TextView[@resource-id='cn.soulapp.android:id/tv_btn' and @text='确认解除']"
    more_menu: "cn.soulapp.android:id/ivChatMore"
    party_hall: "//android.widget.TextView[@resource-id='cn.soulapp.android:id/tv_item' and @text='派对大厅']"
    end_party: "//android.widget.TextView[@resource-id='cn.soulapp.android:id/tv_item' and @text='关闭派对']"
    confirm_end: '//android.widget.TextView[@resource-id="cn.soulapp.android:id/tv_btn" and @text="关闭房间"]'
    more_menu_container: 'cn.soulapp.android:id/moreRootView'
    search_entry: "cn.soulapp.android:id/ivSearch"
    search_box: "cn.soulapp.android:id/commonViewEtSearch"
    search_button: "cn.soulapp.android:id/flRight"
    party_id: "cn.soulapp.android:id/tvFM"
    parties_search: "cn.soulapp.android:id/rvParties"
    grab_mic: "cn.soulapp.android:id/ivUpSeat"
    confirm_mic: "//android.widget.TextView[@resource-id='cn.soulapp.android:id/tv_btn' and @text='确认']"
    toggle_mic: "cn.soulapp.android:id/ivMic"
    square_tab: "cn.soulapp.android:id/main_tab_square"
    party_tab: "//android.widget.LinearLayout[@content-desc='派对']"
    no_party_from_home: "cn.soulapp.android:id/tvEmptyContent"
    no_party_from_hall: "cn.soulapp.android:id/tvEmptyDesc"
    party_search_empty: "cn.soulapp.android:id/llEmpty"
    party_search_result: "cn.soulapp.android:id/searchViewPager"
    party_search_entry: "cn.soulapp.android:id/roomCard"
    content_container: "android:id/content"
    reminder_ok: "cn.soulapp.android:id/tvOk"
    party_back: "cn.soulapp.android:id/tv_look"
    expand_seats: "cn.soulapp.android:id/tvHandleUserList"
    party_online: "cn.soulapp.android:id/tvOnline"
    planet_tab: "cn.soulapp.android:id/main_tab_planet"
    party_hall_entry: '//android.widget.TextView[@resource-id="cn.soulapp.android:id/main_title" and @text="群聊派对"]'
    create_party_entry: "cn.soulapp.android:id/tv_create"
    create_party_button: "cn.soulapp.android:id/createRoomBtn"
    restore_party: "cn.soulapp.android:id/imgRestore"
    confirm_party: "cn.soulapp.android:id/tv_confirm"
    create_party_screen: "cn.soulapp.android:id/rl_room_name"
    claim_reward: "cn.soulapp.android:id/tvCheckReward"

qq_music:
  package_name: "com.tencent.qqmusic"
  search_activity: ".activity.AppStarterActivity"
  elements:
    search_entry: "//androidx.recyclerview.widget.RecyclerView[@resource-id='com.tencent.qqmusic:id/hi2']/android.view.View"
    search_box: "com.tencent.qqmusic:id/searchItem"
    song_tab: "//android.widget.RelativeLayout[@content-desc=\"歌曲 按钮\"]"
    play_button: "com.tencent.qqmusic:id/kcr"
    next_button: "com.tencent.qqmusic:id/f4"
    player_panel: "com.tencent.qqmusic:id/idm"
    back_button: "//android.widget.ImageButton[@content-desc=\"返回\"]"
    song_name: "com.tencent.qqmusic:id/ll6"
    singer_name: "com.tencent.qqmusic:id/ln9"
    pause_button: "android:id/action1"
    skip_button: "android:id/action2"
    playing_bar: "com.tencent.qqmusic:id/iir"
    current_song: "android:id/title"
    current_singer: "android:id/text"
    info_dot: "com.tencent.qqmusic:id/c14"
    details_link: "com.tencent.qqmusic:id/gnw"
    more_in_play_panel: "com.tencent.qqmusic:id/a7m"
    accompaniment_menu: "//android.widget.TextView[@resource-id=\"com.tencent.qqmusic:id/ndp\" and @text=\"伴唱模式\"]"
    accompaniment_switch: "com.tencent.qqmusic:id/ocy"
    song_lyrics: "//android.view.View[@resource-id='js_app']/android.view.View/android.view.View[2]"
    full_lyrics: "//android.view.View[@resource-id='js_app']/android.view.View/android.view.View[2]/android.view.View[last()]"
    accompaniment_status: "com.tencent.qqmusic:id/bln"
#    live_lyrics: "com.tencent.qqmusic:id/e5z"
    live_lyrics: "com.tencent.qqmusic:id/lbr"
    accompaniment_tool: "com.tencent.qqmusic:id/ocx"
    lyrics_tool: "com.tencent.qqmusic:id/hu9"
    lyrics_poster: "//android.widget.TextView[@resource-id='com.tencent.qqmusic:id/jbp' and @text='歌词海报']"
    lyrics_line: "com.tencent.qqmusic:id/h3g"
    lyrics_end: "//android.view.View"
    no_lyrics: "com.tencent.qqmusic:id/ndz"
    clear_search: "com.tencent.qqmusic:id/kpu"
    current_lyrics: "com.tencent.qqmusic:id/kvs"
    content_container: "android:id/content"
    reminder_ok: "com.tencent.qqmusic:id/icm"
    vocal_tag: "//android.widget.TextView[@resource-id='com.tencent.qqmusic:id/n6i' and @text='原唱']"
    accompaniment_tag: "//android.widget.TextView[@resource-id='com.tencent.qqmusic:id/n6i' and @text='伴唱']"
    lyrics_box: "com.tencent.qqmusic:id/j1t"
    close_poster: "com.tencent.qqmusic:id/b5_"
    accompaniment_bar: "com.tencent.qqmusic:id/oct"
    my_nav: '//android.view.ViewGroup[@content-desc="我的"]'
    fav_entry: 'com.tencent.qqmusic:id/i_s'
    play_fav: 'com.tencent.qqmusic:id/eg6'
    fav_song: 'com.tencent.qqmusic:id/ll6'
    fav_singer: 'com.tencent.qqmusic:id/ln9'
    lyrics_tab: '//android.widget.TextView[@resource-id="com.tencent.qqmusic:id/ebb" and @text="歌词"]'
    playlist_tab: '//android.widget.TextView[@resource-id="com.tencent.qqmusic:id/ebb" and @text="歌单"]'
    singer_tab: '//android.widget.TextView[@resource-id="com.tencent.qqmusic:id/ebb" and @text="歌手"]'
    lyrics_text: 'com.tencent.qqmusic:id/h2v'
    playlist_result: 'com.tencent.qqmusic:id/kq5'
    singer_text: 'com.tencent.qqmusic:id/mhi'
    singer_result: 'com.tencent.qqmusic:id/bb9'
    play_playlist: 'com.tencent.qqmusic:id/eg6'
    play_singer: 'com.tencent.qqmusic:id/ehu'
    play_singer_hot: 'com.tencent.qqmusic:id/j0g'
    playlist_item: 'com.tencent.qqmusic:id/ljb'
    go_back: 'com.tencent.qqmusic:id/zu'
    studio_version: '//android.widget.RelativeLayout[@content-desc="录音室版 按钮"]'
    playlist_entry_floating: 'com.tencent.qqmusic:id/iit'
    playlist_entry_playing: 'com.tencent.qqmusic:id/a8f'
    playlist_song: 'com.tencent.qqmusic:id/llj'
    playlist_singer: 'com.tencent.qqmusic:id/l9n'
    playlist_playing: 'com.tencent.qqmusic:id/e_s'
    playlist_title: 'com.tencent.qqmusic:id/j4l'
commands:
  - prefix: "play"
    response_template: "Playing {song} by {singer}"
  - prefix: "skip"
    response_template: "Skipped {song} by {singer}"
  - prefix: "next"
    response_template: "Added {song} by {singer} to playlist"
  - prefix: "pause"
    response_template: "{action} {song} by {singer}"
    error_template: "Failed to {action}, because {error}"
  - prefix: "vol"
    response_template: "Current volume is {level}"
    increase_template: "Volume increased by {times} level, current volume is {level}"
    decrease_template: "Volume decreased by {times} level, current volume is {level}"
    error_template: "Failed to adjust volume, because {error}"
  - prefix: "acc"
    response_template: "Accompaniment mode {enabled}"
    error_template: "Failed to toggle accompaniment mode, because {error}"
  - prefix: "lyrics"
    response_template: "{lyrics}"
    error_template: "Failed to get lyrics, because {error}"
  - prefix: "ktv"
    response_template: "KTV mode {enabled}"
    error_template: "Failed to toggle KTV mode, because {error}"
  - prefix: "enable"
    response_template: "Enabled: {enabled}"
  - prefix: "help"
    response_template:  |
      Help for (U)Share (I)Play
      1. play - play music and change the playlist
        command - :play keywords
      2. next - queue up music to next, first come first serve, won't change playlist
        command - :next keywords
      3. acc - turn on/off accompaniment mode, apply on the playlist
        command - :acc 1/0
      4. skip - play next song instantly
        command - :skip
      5. pause - pause/play current song
        command - :pause 1/0
      6. vol - Adjust volume  by n level, if n is negative, it means decrease
        command - :vol n
  - prefix: "invite"
    response_template: "Invited by {user} to party {party_id}"
    error_template: "Failed to join party {party_id}, because {error}"
  - prefix: "admin"
    response_template: "Invited {user} as administrator"
    error_template: "Failed to invite {user} as administrator, because {error}"
  - prefix: "info"
    response_template: "Playing: {song} by {singer}\nAlbum: {album}"
    error_template: "Failed to get playback info, because {error}"
  - prefix: "singer"
    response_template: "Playing singer {singer}"
    error_template: "Failed to play singer, because {error}"
  - prefix: "playlist"
    response_template: "Playing playlist {playlist}"
    current_template: "Playlist\n{playlist}"
    error_template: "Failed to play playlist, because {error}"
appium:
  host: "192.168.50.103"
  port: 4723

device:
  name: "192.168.50.151:5555"
  platform_name: "Android"
  platform_version: "10"
  automation_name: "UiAutomator2"
  no_reset: true 
