soul:
  package_name: "cn.soulapp.android"
  chat_activity: ".cpnt_voiceparty.soulhouse.SoulHouseActivity"
  elements:
    message_list: "cn.soulapp.android:id/rvMessage"
    message_content: "cn.soulapp.android:id/tvContent"
    input_box_entry: "cn.soulapp.android:id/tvChat"
    input_box: "cn.soulapp.android:id/etInputView"
    button_send: "cn.soulapp.android:id/btnSend"

qq_music:
  package_name: "com.tencent.qqmusic"
  search_activity: ".activity.AppStarterActivity"
  elements:
    search_entry: "//androidx.recyclerview.widget.RecyclerView[@resource-id=\"com.tencent.qqmusic:id/hi2\"]/android.view.View"
    search_box: "com.tencent.qqmusic:id/searchItem"
    play_button: "com.tencent.qqmusic:id/krg"
    next_button: "com.tencent.qqmusic:id/f4"
    player_panel: "com.tencent.qqmusic:id/idm"
    back_button: "//android.widget.ImageButton[@content-desc=\"返回\"]"
    song_name: "com.tencent.qqmusic:id/ll6"
    singer_name: "com.tencent.qqmusic:id/ln9"
    pause_button: "android:id/action1"
    skip_button: "android:id/action2"
    playing_bar: "com.tencent.qqmusic:id/iir"
    current_song: "android:id/title"
    current_singer: "android:id/text"
    info_dot: "com.tencent.qqmusic:id/c14"
    details_link: "com.tencent.qqmusic:id/gnw"
    more_in_play_panel: "com.tencent.qqmusic:id/a7m"
    accompaniment_menu: "//android.widget.TextView[@resource-id=\"com.tencent.qqmusic:id/ndp\" and @text=\"伴唱模式\"]"
    accompaniment_switch: "com.tencent.qqmusic:id/ocy"
    song_lyrics: "//android.view.View[@resource-id='js_app']/android.view.View/android.view.View[2]"
commands:
  - prefix: "play"
    response_template: "Playing <<{song}>> by {singer}"
  - prefix: "skip"
    response_template: "Skipped to next song <<{song}>> by {singer}"
  - prefix: "next"
    response_template: "Scheduled {song} by {singer} to play next"
  - prefix: "pause"
    response_template: "Paused/Playing <<{song}>> by {singer}"
  - prefix: "vol+"
    response_template: "Volume increased"
  - prefix: "accompaniment"
    response_template: "Accompaniment mode {enabled}"
  - prefix: "lyrics"
    response_template: "{lyrics}"
    tags: ["歌曲名", "歌手", "语种", "专辑", "专辑发行时间", "幕后团队", "作词", "作曲", "歌词", "制作人", “歌曲简介”]

appium:
  host: "0.0.0.0"
  port: 4723

device:
  name: "554b4e4745413498"
  platform_name: "Android"
  platform_version: "10"
  automation_name: "UiAutomator2"
  no_reset: true 