soul:
  package_name: "cn.soulapp.android"
  chat_activity: ".cpnt_voiceparty.soulhouse.SoulHouseActivity"
  elements:
    message_list: "cn.soulapp.android:id/rvMessage"
    message_content: "cn.soulapp.android:id/tvContent"
    input_box_entry: "cn.soulapp.android:id/tvChat"
    input_box: "cn.soulapp.android:id/etInputView"
    button_send: "cn.soulapp.android:id/btnSend"
    new_message_tip: "cn.soulapp.android:id/tvNewMsgTip"
    floating_entry: "cn.soulapp.android:id/background"
    invite_link: "cn.soulapp.android:id/iv_room_music"
    sender_relation: "cn.soulapp.android:id/imgRelation"
    sender_flag: "cn.soulapp.android:id/flagContainerView"
    sender_avatar: "cn.soulapp.android:id/ivAvatar"
    sender_nickname: "cn.soulapp.android:id/tvNickname"
    profile_avatar: "cn.soulapp.android:id/img_head"
    moments_chat: "cn.soulapp.android:id/rl_user_bottom_chat"
    chat_title: "cn.soulapp.android:id/c_ct_chat_title_info"
    manager_invite: "cn.soulapp.android:id/tv_manager_invite"
    confirm_invite: "cn.soulapp.android:id/tv_confirm_invite"
    confirm_dismiss: "//android.widget.TextView[@resource-id='cn.soulapp.android:id/tv_btn' and @text='确认解除']"
    more_menu: "cn.soulapp.android:id/ivChatMore"
    party_hall: "//android.widget.TextView[@resource-id='cn.soulapp.android:id/tv_item' and @text='派对大厅']"
    search_entry: "cn.soulapp.android:id/ivSearch"
    search_box: "cn.soulapp.android:id/commonViewEtSearch"
    search_button: "cn.soulapp.android:id/flRight"
    party_id: "cn.soulapp.android:id/tvFM"
    parties_search: "cn.soulapp.android:id/rvParties"
    grab_mic: "cn.soulapp.android:id/ivUpSeat"
    confirm_mic: "//android.widget.TextView[@resource-id='cn.soulapp.android:id/tv_btn' and @text='确认']"
    toggle_mic: "cn.soulapp.android:id/ivMic"

qq_music:
  package_name: "com.tencent.qqmusic"
  search_activity: ".activity.AppStarterActivity"
  elements:
    search_entry: "//androidx.recyclerview.widget.RecyclerView[@resource-id='com.tencent.qqmusic:id/hi2']/android.view.View"
    search_box: "com.tencent.qqmusic:id/searchItem"
    song_tab: "//android.widget.RelativeLayout[@content-desc=\"歌曲 按钮\"]"
    play_button: "com.tencent.qqmusic:id/kcr"
    next_button: "com.tencent.qqmusic:id/f4"
    player_panel: "com.tencent.qqmusic:id/idm"
    back_button: "//android.widget.ImageButton[@content-desc=\"返回\"]"
    song_name: "com.tencent.qqmusic:id/ll6"
    singer_name: "com.tencent.qqmusic:id/ln9"
    pause_button: "android:id/action1"
    skip_button: "android:id/action2"
    playing_bar: "com.tencent.qqmusic:id/iir"
    current_song: "android:id/title"
    current_singer: "android:id/text"
    info_dot: "com.tencent.qqmusic:id/c14"
    details_link: "com.tencent.qqmusic:id/gnw"
    more_in_play_panel: "com.tencent.qqmusic:id/a7m"
    accompaniment_menu: "//android.widget.TextView[@resource-id=\"com.tencent.qqmusic:id/ndp\" and @text=\"伴唱模式\"]"
    accompaniment_switch: "com.tencent.qqmusic:id/ocy"
    song_lyrics: "//android.view.View[@resource-id='js_app']/android.view.View/android.view.View[2]"
    full_lyrics: "//android.view.View[@resource-id='js_app']/android.view.View/android.view.View[2]/android.view.View[last()]"
    accompaniment_tag: "com.tencent.qqmusic:id/n6i"
#    live_lyrics: "com.tencent.qqmusic:id/e5z"
    live_lyrics: "com.tencent.qqmusic:id/lbr"
commands:
  - prefix: "play"
    response_template: "Playing <<{song}>> by {singer}"
  - prefix: "skip"
    response_template: "Skipped to next song <<{song}>> by {singer}"
  - prefix: "next"
    response_template: "Scheduled {song} by {singer} to play next"
  - prefix: "pause"
    response_template: "Paused/Resume <<{song}>> by {singer}"
    error_template: "Pause failed, because {error}"
  - prefix: "vol+"
    response_template: "Volume increased"
  - prefix: "acc"
    response_template: "Accompaniment mode {enabled}"
#  - prefix: "lyrics"
#    response_template: "{lyrics}"
#    tags: ["歌曲名", "歌手", "语种", "专辑", "专辑发行时间", "幕后团队", "作词", "作曲", "歌词", "制作人", "歌曲简介", "影视综述"]
  - prefix: "ktv"
    response_template: "{lyrics}"
    max_switches: 9
    switch_interval: 1
  - prefix: "enable"
    response_template: "Enabled: {enabled}"
  - prefix: "help"
    response_template:  |
      Help for (U)Share (I)Play
      1. play - play music and change the playlist
        command - :play keywords
      2. next - queue up music to next, first come first serve, won't change playlist
        command - :next keywords
      3. acc - turn on/off accompaniment mode, apply on the playlist
        command - :acc 1/0
      4. skip - play next song instantly
        command - :skip
      5. pause - pause/play current song
        command - :pause 1/0
      6. vol - volume up/down by one level 
        command - :vol+/-
  - prefix: "invite"
    response_template: "Invited by {user} to party {party_id}"
    error_template: "Failed to join party {party_id}, because {error}"
  - prefix: "admin"
    response_template: "Invited {user} as administrator"
    error_template: "Failed to invite {user} as administrator, because {error}"
appium:
  host: "192.168.50.103"
  port: 4723

device:
  name: "192.168.50.151:5555"
  platform_name: "Android"
  platform_version: "10"
  automation_name: "UiAutomator2"
  no_reset: true 
